server:
  port: 9002
eureka:
  instance:
    prefer-ip-address: true
    status-pageDto-url-path: /actuator/info #eureka注册中心的url link
    health-check-url-path: /actuator/health #健康检查的url
  client:
    eureka-server-port: 9000
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://andawell:andawell@registry-center:${eureka.client.eureka-server-port}/eureka/

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@orcl-auth-server:1521:orcl
    username: AW235A
    password: AW235A
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  transaction:
    rollback-on-commit-failure: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000


security:
  oauth2:
    client:
      client-id: andawell
      client-secret: andawell
      scope: server
      # 默认放行url,子模块重写时application-dev.yml中的公共配置会被覆盖,所以要把公共配置中的放行url再写一次
      ignore-urls:
        - /actuator/**
        - /v2/api-docs