server:
  port: 9001
eureka:
  instance:
    prefer-ip-address: true
    status-pageDto-url-path: /actuator/info #eureka注册中心的url link
    health-check-url-path: /actuator/health #健康检查的url
  client:
    eureka-server-port: 9000
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://andawell:andawell@registry-center:${eureka.client.eureka-server-port}/eureka/
spring:
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
        - id: upms
          uri: lb://upms-service
          predicates:
            - Path=/upms/**
          filters:
            - AddRequestHeader=AuthFlag, true
            - SwaggerHeaderFilter
            #- VerifyHeaderFilter
            - StripPrefix=1
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - AddRequestHeader=AuthFlag, true
            - SwaggerHeaderFilter
            - StripPrefix=1
        - id: material
          uri: lb://material-service
          predicates:
            - Path=/material/**
          filters:
            - AddRequestHeader=AuthFlag, true
            - SwaggerHeaderFilter
            - StripPrefix=1
        - id: search
          uri: lb://search-service
          predicates:
            - Path=/search/**
          filters:
            - AddRequestHeader=AuthFlag, true
            - SwaggerHeaderFilter
            - StripPrefix=1
        - id: purchase
          uri: lb://purchase-service
          predicates:
            - Path=/purchase/**
          filters:
            - AddRequestHeader=AuthFlag, true
            - SwaggerHeaderFilter
            - StripPrefix=1
        - id: report
          uri: lb://report-service
          predicates:
            - Path=/report/**
          filters:
            - AddRequestHeader=AuthFlag, true
            - SwaggerHeaderFilter
            - StripPrefix=1

