#########################测试环境信息配置
server:
  port: 9001
eureka:
  instance:
    prefer-ip-address: true
    status-pageDto-url-path: /actuator/info #eureka注册中心的url link
    health-check-url-path: /actuator/health #健康检查的url
    hostname: registry-center
  client:
    eureka-server-port: 90000
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://andawell:andawell@${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/